---
  # nmcli conn add type ovs-bridge conn.interface bridge0 autoconnect yes
  # nmcli conn add type ovs-port conn.interface port0 master bridge0 autoconnect yes

  # nmcli conn add type ovs-interface conn.interface iface0 master port0 autoconnect yes ipv4.method auto
  # nmcli conn add type ovs-port conn.interface port1 master bridge0 autoconnect yes
    
- name: create bridge userspace
  ansible.builtin.shell: |
    nmcli conn add type ovs-bridge conn.interface {{ ovs_bridge }} autoconnect {{ autoconnect }}  
    nmcli conn add type ovs-port conn.interface {{ connection_port }} master  {{ ovs_bridge }} autoconnect {{ autoconnect }}
    nmcli conn add type ovs-interface conn.interface {{ ovs_bridge }} master {{ connection_port }} autoconnect {{ autoconnect }} ipv4.method auto
    nmcli conn add type ovs-port conn.interface {{ interface_port }} master {{ ovs_bridge }} autoconnect {{ autoconnect }}
    nmcli conn down {{ ovs_bridge }}
    {% if ipv4_method != "auto" %}
    nmcli connection modify ovs-slave-{{ ovs_bridge }} ipv4.method {{ ipv4_method }} ipv4.address {{ ipv4_address }} ipv4.gateway {{ ipv4_gateway }} 
    {% endif %}