---
#nmcli conn add type ethernet conn.interface {{ physical_nic }} master {{ interface_port }} autoconnect yes && ip addr flush dev {{ physical_nic }} && reboot
- name: add nic to bridge
  ansible.builtin.shell: |
    nmcli conn add type ethernet conn.interface {{ physical_nic }} master {{ interface_port }} autoconnect yes && ip addr flush dev {{ physical_nic }} && nmcli con up ovs-slave-{{ physical_nic }} && ip addr add {{ ipv4_address }} dev {{ ovs_bridge }}


# why doesnt this work? it starts the interface, but it requires reboot to work and that the nic is part of the ovs-slave-<physical nic> gets added as a connection and to show up in nmcli con show
